### ISSUE TITLE
Changes to the homepage do not stage as expected

### ISSUE THREAD

**Issue by thepegisin** [cagov/drought.ca.gov#127] opened 2021-09-29 21:26 UTC
When staging changes to the homepage, the content publishes all the way up to production. This is hampering our ability to have stakeholders preview a change before it's published.

See Slack thread when this last happened: https://cadotgov.slack.com/archives/C02F10G3L94/p1632507531002300

**Comment by wrendo** [comment] 2021-09-29 22:25
Carter has been working on a preview function and Chach has been working on consolidating the functionality into the publishing engineering pipeline. I believe she's working on UI elements for this.

**Comment by jbum** [comment] 2021-09-29 22:36
Jim to test if the staging tag is working as expected.

**Comment by jbum** [comment] 2021-09-30 00:21
I believe the problem is the use of the **staging** tag.  The correct tag (at the moment) is **staging-only**.  "staging" is ignored, and treated as a production update.

**Comment by jbum** [comment] 2021-09-30 23:01
It's possible today's fixes alleviated this.  Testing...

**Comment by jbum** [comment] 2021-09-30 23:29
Staging publishing of homepage is working in my tests.

**Comment by jbum** [comment] 2021-10-01 16:31
Removing p0 tag since I believe this is performing better now.

**Comment by abquirarte** [comment] 2021-10-01 18:04
@jbum tagging you on this. How is it better? Can you summarize here? :) 
I think we've never been able to stage anything on the homepage. 

cc @thepegisin you can expand here.

**Comment by jbum** [comment] 2021-10-06 17:27
Closing as underlying cause is same as #130.  Using #130 for all related symptoms.

**Closed by jbum** 2021-10-06 17:27 UTC
Labels: Tech, bug, Headless publishing
