### ISSUE TITLE
Fix layout of h1 on pages with left sidebar

### ISSUE THREAD

**Issue by adam-little** [cagov/drought.ca.gov#95] opened 2021-08-02 21:54 UTC
The position of the h1 on pages that have a left sidebar is not correct. See examples below:

![image](https://user-images.githubusercontent.com/69167298/127928578-d8288bcf-5996-4425-8c20-1950ce5abc71.png)
![image](https://user-images.githubusercontent.com/69167298/127928600-14d7141e-9818-4b8d-8d11-ce0478ec661f.png)

H1 should be positioned above main content. See  example below: 
![image](https://user-images.githubusercontent.com/69167298/127928656-2d973876-37dd-4f42-aab6-b68f78af0dd6.png)

**Comment by jaredwyee** [comment] 2021-08-04 16:29
Thanks Adam. Assigned to Jim as workable not urgent.

**Comment by jbum** [comment] 2021-08-12 18:44
@adam-little when you get a moment, could you do a mock up of how you want it to look with one of these large hero images?  If I do a straight-forward adoption of your suggestion, it's looking a little odd.  Not sure if you want the baselines or the top-lines to line up for the smaller/larger titles at the top...

![image](https://user-images.githubusercontent.com/287977/129251280-bc8469e0-ec93-46cd-aa8f-27ed2615b71b.png)

**Comment by adam-little** [comment] 2021-08-12 21:31
This is what we have in[ Figma](https://www.figma.com/file/9FTGOPO5HlsLfYuNrtL9IM/Design-System-Projects?node-id=2820%3A10023). The hero image appears below the H1. 

Part of the reason we want to keep the left sidebar separate from the page content is so that the left-side navigation can become sticky [that will be another issue for another day]

![image](https://user-images.githubusercontent.com/69167298/129272571-d7332db0-1593-46e2-a22d-9677b221d5cf.png)

**Comment by adam-little** [comment] 2021-08-17 17:38
Here are examples of the correct layout on Cannabis:

- With sidebar: https://cannabis.ca.gov/licensees/cultivation/
- With no sidebar: https://cannabis.ca.gov/about-us/announcements/

**Comment by chachasikes** [comment] 2021-08-17 19:12
Notes
(and also I might be picking this up for Jim)

* We have page templates, or layouts.
* The layouts include two titles, mobile & desktop, which have different locations in the markup (and which also had to work with the CAWeb theme for WordPress (which has some overhead)
* We can make sure the correct template is used on the page (I assume it is, but let's double check)
* We can make sure that any changes to the design system features did not revert this behavior (and that the showing/hiding of the title is correct)

**Comment by jbum** [comment] 2021-08-30 22:15
Assigning to Chach as I believe she has already done some work on this.

**Comment by jbum** [comment] 2021-11-01 23:10
I'm having an issue with fixing this one, possibly caused by lack of understanding how the CSS system works here.  I can see that in _page.scss, there is a block of CSS that needs to be conditionally triggered to swap between wide-page-title and narrow-page-title only when the page is narrow.  At the moment, we ALWAYS see narrow-page-title.

I can see in _pages.scss, that the below section is always triggering, and always causing the 'narrow-page-title' to be displayed.  Normally we would only want this displayed when we switch to a narrower layout.

```
  .wide-page-title {
    display: none;
  }

  .narrow-page-title {
    display: block;
    margin-bottom: 16px;
    margin-top: 16px;
  }
```

So the above block needs to inside something like
```
@media (max-width: 759px) {
}
```

However (this is the weird part), when I test locally, _none_ of the changes I make to that block seem to have any effect. It is as if I am pulling the CSS from some other external location other than my local copy of the repository. Even if I completely comment out the above block, the narrow-page-title still displays, even though nothing in that block indicates it should.  This is very different than the behavior I'm used to with Covid-19, where I can make edits to the local css and see the effect.

@chachasikes, @kkoryaka, @xjensen  do you have any idea what is going on here?

**Comment by xjensen** [comment] 2021-11-02 00:15
> It is as if I am pulling the CSS from some other external location other than my local copy of the repository.

You got it. [This CSS](https://github.com/cagov/design-system/blob/2039f72bea418e8dfdb7940bba6e8127e3408e02/components/base-css/src/_page.scss#L68-L77) is getting pulled from the `ds-base-css` component in the Design System. It's inserted into Drought's Sass pipeline [here](https://github.com/cagov/drought.ca.gov/blob/1a1f2a6c698a2134c44859466ea87f6611731605/src/css/sass/index.scss#L8). 

So to test out changes, you're getting into the very fun and never-frustrating world of locally testing the Design System. I'd be happy to meet up to show you how I do this on Drought and Cannabis. Others may have better techniques too.

One of the other problems is that we've got a lot of redundant code in Drought's repo that needs to be removed. A lot of that Sass and CSS doesn't do anything anymore. Cleaning it up is on my list of things to do, just hasn't been a priority yet.

**Comment by jbum** [comment] 2021-11-04 16:44
@kkoryaka could you take a look at this?  I'm having a hard time figuring out why it's behaving differently than Cannabis, despite similar style and layout.

**Comment by kkoryaka** [comment] 2021-11-09 21:42
@adam-little please review in staging: https://staging.drought.ca.gov/state-drought-response/

**Comment by adam-little** [comment] 2021-11-10 18:35
Looks good @kkoryaka thank you

**Comment by kkoryaka** [comment] 2021-11-10 22:33
This is done: https://drought.ca.gov/state-drought-response/

**Closed** 2021-11-10 22:33 UTC
Labels: Tech, P1
