### ISSUE TITLE
Handle no-robots

### ISSUE THREAD

**Issue by chachasikes** [cagov/drought.ca.gov#192] opened 2021-10-27 16:21 UTC
Drought development instances s3 buckets do NOT have index disallowing robots.txt files:
* How do we want to handle no robots copying from other branches?
* maybe robots.copyme.txt & no-robots.copyme.txt write & get renamed to robots.txt by branch?
* Suggestion: connect robot copying to yml settings

**Comment by aaronhans** [comment] 2021-11-10 23:28
Good suggestions on how to handle this programatically

I added notes to https://github.com/cagov/odi-engineering/wiki/Setting-up-a-new-headless-site-instance to add robots file with permissions defaulting to disallow

Thanks for thinking about this in https://github.com/cagov/odi-engineering/issues/53 @xjensen 

The cannabis site has robots files disallowing crawling in all branches now because it does not allow crawling anywhere and the covid site has the appropriate nocrawl directives

nocrawls were missing on covid staging and messed up in preproduction. I fixed them.

Moving this ticket to backlog so we can prioritize the programmatic solution as part of the build process which will help ensure we don't mess this up in the future.

**Comment by xjensen** [comment] 2021-11-17 00:29
This has partly been addressed as part of the per-PR site preview function at #211. See [this robots.txt code](https://github.com/cagov/drought.ca.gov/blob/e60aa0b120f41865afb93779c861b6ffdb4fcd1b/.github/workflows/eleventy_build_pr.yml#L26-L29) in the corresponding GitHub Action.

We could easily add this step to other non-`main` GitHub Actions. I'll do that.

Going forward, we could consider consolidating the `staging`, `development`, and other non-`main` branches into the same mechanism that drives per-PR preview sites. But not yet. I think we need to give this new feature a little time to prove itself.

**Closed** 2021-11-29 21:21 UTC
Labels: P1
